# Generated by Django 5.1.5 on 2025-02-06 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuser",
            name="note",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("1"), "1"),
                    (Decimal("2"), "2"),
                    (Decimal("3"), "3"),
                    (Decimal("4"), "4"),
                    (Decimal("5"), "5"),
                ],
                decimal_places=1,
                default=Decimal("0"),
                max_digits=2,
                null=True,
            ),
        ),
    ]
