# Generated by Django 5.1.5 on 2025-02-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationavis",
            name="commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.noteuser",
                verbose_name="Avis du passager",
            ),
        ),
        migrations.AlterField(
            model_name="moderationavis",
            name="commentaire_moderer",
            field=models.BooleanField(default=False),
        ),
    ]
