# Generated by Django 5.1.5 on 2025-04-05 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_noteuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuser",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
