# Generated by Django 5.1.5 on 2025-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_moderationavis_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationavis",
            name="commentaire",
            field=models.TextField(
                blank=True, null=True, verbose_name="Avis du passager"
            ),
        ),
    ]
