# Generated by Django 5.1.5 on 2025-02-22 20:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_moderationavis_commentaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModerationAvis",
        ),
        migrations.AddField(
            model_name="noteuser",
            name="commentaire_moderer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="decision_prise",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="etat_paiement",
            field=models.CharField(
                choices=[("Payer", "Payer"), ("Refuser", "Refuser")],
                default="Payer",
                max_length=20,
                verbose_name="Statut du paiement",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="avis",
            field=models.CharField(
                choices=[("oui", "oui"), ("non", "non")],
                default="oui",
                max_length=100,
                verbose_name="Ça s'est bien passé ?",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="note",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("1"), "1"),
                    (Decimal("2"), "2"),
                    (Decimal("3"), "3"),
                    (Decimal("4"), "4"),
                    (Decimal("5"), "5"),
                ],
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="Note attribuée",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noteuser",
            unique_together={("chauffeur", "passager", "trajet")},
        ),
    ]
