# Generated by Django 5.1.5 on 2025-02-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_noteuser_chauffeur_alter_noteuser_trajet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationtrajet",
            name="prix_par_passager",
        ),
    ]
