# Generated by Django 5.1.5 on 2025-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_moderationavis_noteuser_commentaire_moderer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="avis_donne",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="commentaire_attribuee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="note_attribuee",
            field=models.BooleanField(default=False),
        ),
    ]
