# Generated by Django 5.1.5 on 2025-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_reservationtrajet_prix_par_passager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationtrajet",
            name="etat_reservation",
            field=models.CharField(
                choices=[
                    ("Reserver", "Réservé"),
                    ("En cours", "Demarrer"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="etat_reservations",
                max_length=50,
            ),
        ),
    ]
