# Generated by Django 5.1.5 on 2025-02-22 23:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_noteuser_avis_donne_noteuser_commentaire_attribuee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="avis_donne",
            field=models.BooleanField(default=False, verbose_name="Avis donné ?"),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="commentaire_attribuee",
            field=models.BooleanField(default=False, verbose_name="Commenté ?"),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="decision_prise",
            field=models.BooleanField(default=False, verbose_name="Administré ?"),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="note_attribuee",
            field=models.BooleanField(default=False, verbose_name="Noté ?"),
        ),
    ]
