# Generated by Django 5.1.5 on 2025-03-04 18:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_noteuser_token_alter_noteuser_avis_donne_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuser",
            name="commentaire",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commentaire laissé"
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="note",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("1"), "1"),
                    (Decimal("2"), "2"),
                    (Decimal("3"), "3"),
                    (Decimal("4"), "4"),
                    (Decimal("5"), "5"),
                ],
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="Note",
            ),
        ),
    ]
