# Generated by Django 5.1.5 on 2025-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_reservationtrajet_etat_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationtrajet",
            name="prix_par_passager",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="changerstatuttrajet",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("En cours", "Demarrer"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="Disponible",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="avis",
            field=models.CharField(
                choices=[("oui", "oui"), ("non", "non")], default="oui", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="reservationtrajet",
            name="etat_reservation",
            field=models.CharField(
                choices=[
                    ("Reserver", "Réservé"),
                    ("En cours", "Demarrer"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="etat_reservations",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trajetproposer",
            name="etat",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("En cours", "Demarrer"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="Disponible",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="trajetproposer",
            name="type_moteur",
            field=models.CharField(
                choices=[
                    ("Electrique", "Electrique"),
                    ("Hybride", "Hybride"),
                    ("essence", "Essence"),
                    ("diesel", "Diesel"),
                ],
                max_length=15,
            ),
        ),
    ]
