# Generated by Django 5.1.5 on 2025-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_reservationtrajet_prix_par_passager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationtrajet",
            name="places",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 place"),
                    (2, "2 places"),
                    (3, "3 places"),
                    (4, "4 places"),
                    (5, "5 places"),
                    (6, "6 places"),
                ],
            ),
        ),
    ]
