# Generated by Django 5.1.5 on 2025-02-06 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_reservationtrajet_passager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trajetproposer",
            name="total_payer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationtrajet",
            name="etat_reservation",
            field=models.CharField(
                choices=[
                    ("Reserver", "Réservé"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="Reserver",
                max_length=20,
            ),
        ),
    ]
