# Generated by Django 5.1.5 on 2025-02-09 21:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_trajetproposer_total_payer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adresseuser",
            options={
                "verbose_name": "Information sur l'utilisateur",
                "verbose_name_plural": "Informations sur les utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="changerstatuttrajet",
            options={
                "verbose_name": "Changer le statut du trajet",
                "verbose_name_plural": "Changer les statuts des trajets",
            },
        ),
        migrations.AlterModelOptions(
            name="choixrole",
            options={
                "verbose_name": "Role utilisateur",
                "verbose_name_plural": "Roles utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="credituser",
            options={
                "verbose_name": "Crédit utilisateur",
                "verbose_name_plural": "Crédits utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="noteuser",
            options={
                "verbose_name": "Note utilisateur",
                "verbose_name_plural": "Notes utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="preference",
            options={
                "verbose_name": "Préférence de l'utilisateur",
                "verbose_name_plural": "Préférences des utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationtrajet",
            options={
                "verbose_name": "Réservation de trajet",
                "verbose_name_plural": "Réservations de trajets",
            },
        ),
        migrations.AlterModelOptions(
            name="trajetproposer",
            options={
                "verbose_name": "Trajet proposé",
                "verbose_name_plural": "Trajets proposés",
            },
        ),
        migrations.AlterModelOptions(
            name="voiture",
            options={"verbose_name": "Voiture", "verbose_name_plural": "Voitures"},
        ),
        migrations.RemoveField(
            model_name="trajetproposer",
            name="commission",
        ),
        migrations.RemoveField(
            model_name="trajetproposer",
            name="places_reservees",
        ),
        migrations.AlterField(
            model_name="adresseuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresse_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="choixrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="credituser",
            name="credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Crédit actuel de l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="credituser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="avis",
            field=models.CharField(
                choices=[("oui", "oui"), ("non", "non")],
                default="oui",
                max_length=100,
                verbose_name="sa c'est bien passé ?",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="chauffeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accusé",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chauffeur",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="commentaire",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commentaire du concerné"
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="note",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("1"), "1"),
                    (Decimal("2"), "2"),
                    (Decimal("3"), "3"),
                    (Decimal("4"), "4"),
                    (Decimal("5"), "5"),
                ],
                decimal_places=1,
                default=Decimal("0"),
                max_digits=2,
                null=True,
                verbose_name="Note attribuée",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="passager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jury",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Passager",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="trajet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bout_du_tunnel",
                to="main.trajetproposer",
                verbose_name="Trajet concerné",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="animaux",
            field=models.CharField(
                choices=[
                    ("Animaux", "animaux autorisé"),
                    ("Pas_d'animaux", "pas d'animaux"),
                ],
                default="Animaux",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="exigences_particulieres",
            field=models.CharField(
                choices=[
                    ("silence", "Silence pendant le trajet"),
                    ("bagages_limites", "Bagages limités"),
                    ("musique", "Musique pendant le trajet"),
                    ("ponctualite", "Ponctualité obligatoire"),
                    ("nourriture_non_autorisee", "Pas de nourriture à bord"),
                    ("conduite_partagee", "Partager la conduite"),
                ],
                default="Pas d'exigences particulières",
                max_length=50,
                verbose_name="Preference en plus",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="exigences_personnelles",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Preferences personnelles",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="fumeur",
            field=models.CharField(
                choices=[("Fumeur", "fumeur accepté"), ("Non\x0cumeur", "non fumeur")],
                default="Non_fumeur",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="user_preference",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur concerné",
            ),
        ),
        migrations.AlterField(
            model_name="trajetproposer",
            name="type_moteur",
            field=models.CharField(
                choices=[
                    ("Electrique", "Electrique"),
                    ("Hybride", "Hybride"),
                    ("essence", "Essence"),
                    ("diesel", "Diesel"),
                ],
                max_length=15,
                verbose_name="Moteur",
            ),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="type_moteur",
            field=models.CharField(
                choices=[
                    ("Electrique", "Electrique"),
                    ("Hybride", "Hybride"),
                    ("essence", "Essence"),
                    ("diesel", "Diesel"),
                ],
                max_length=50,
                verbose_name="Moteur",
            ),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voiture",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.DeleteModel(
            name="TokenConfirmationTrajetTermine",
        ),
    ]
