# Generated by Django 5.1.5 on 2025-02-09 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_adresseuser_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresseuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="adresse_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="changerstatuttrajet",
            name="trajet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statut",
                to="main.trajetproposer",
            ),
        ),
        migrations.AlterField(
            model_name="choixrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="chauffeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accusé",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chauffeur",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="passager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jury",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Passager",
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="trajet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bout_du_tunnel",
                to="main.trajetproposer",
                verbose_name="Trajet concerné",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="user_preference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur concerné",
            ),
        ),
        migrations.AlterField(
            model_name="reservationtrajet",
            name="passager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_passager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationtrajet",
            name="trajet_reserver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="main.trajetproposer",
            ),
        ),
        migrations.AlterField(
            model_name="trajetproposer",
            name="voiture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voiture",
                to="main.voiture",
            ),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voiture",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
