# Generated by Django 5.1.5 on 2025-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_adresseuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationtrajet",
            name="etat_reservation",
            field=models.CharField(
                choices=[
                    ("Reserver", "Réservé"),
                    ("Terminé", "Terminé"),
                    ("Annulé", "Annulé"),
                ],
                default="Reserver",
                max_length=20,
                verbose_name="Etat de la réservation",
            ),
        ),
    ]
