# Generated by Django 5.1.5 on 2025-02-12 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_reservationtrajet_etat_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresseuser",
            name="numero",
            field=models.CharField(max_length=10, verbose_name="Numéro du batiment"),
        ),
        migrations.AlterField(
            model_name="adresseuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="main/profils_picture/photo_default/photo_default.jpg",
                null=True,
                upload_to="user",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="trajetproposer",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix par passager",
            ),
        ),
    ]
