from .etape_connection.etape1 import PremierEtape
from .etape_connection.etape2 import DeuxiemeEtape
from .autorisation_access.all_access import is_superuser_or_moderateur
from .autorisation_access.admin_access import Admin_access
from .suppression_compte.suppression_compte import SuppressionCompte
