# Generated by Django 5.1.5 on 2025-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiture",
            name="modele",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
