# Generated by Django 5.1.5 on 2025-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tokenvalidation",
            old_name="token",
            new_name="session_token",
        ),
        migrations.AddField(
            model_name="tokenvalidation",
            name="code_2fa",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
