# Generated by Django 5.1.5 on 2025-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_voiture_modele"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresseuser",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
