# Generated by Django 5.1.5 on 2025-11-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_rename_token_tokenvalidation_session_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenvalidation",
            name="code_2fa",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
