
BEGIN;
--
-- Create model ActivationToken
--
CREATE TABLE "main_activationtoken" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" varchar(100) NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "user_id" integer NOT NULL UNIQUE);
--
-- Create model AdresseUser
--
CREATE TABLE "main_adresseuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "numero" varchar(10) NOT NULL, "type_voie" varchar(100) NOT NULL, "nom_rue" varchar(100) NOT NULL, "complement" varchar(100) NULL, "code_postal" integer NOT NULL, "ville" varchar(100) NOT NULL, "pays" varchar(100) NOT NULL, "telephone" varchar(10) NULL, "email" varchar(100) NULL, "photo" varchar(100) NULL, "user_id" integer NOT NULL UNIQUE);
--
-- Create model ChoixRole
--
CREATE TABLE "main_choixrole" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role" varchar NOT NULL, "user_id" integer NOT NULL UNIQUE);
--
-- Create model CreditUser
--
CREATE TABLE "main_credituser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "credit" numeric(10, 2) NOT NULL, "user_id" integer NOT NULL UNIQUE);
--
-- Create model Preference
--
CREATE TABLE "main_preference" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "exigences_particulieres" varchar(50) NOT NULL, "exigences_personnelles" text NULL, "fumeur" varchar(50) NOT NULL, "animaux" varchar(50) NOT NULL, "user_preference_id" integer NULL UNIQUE);
--
-- Create model ReservationTrajet
--
CREATE TABLE "main_reservationtrajet" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "prix_par_passager" numeric(5, 2) NOT NULL, "places" integer NULL, "etat_reservation" varchar(20) NOT NULL, "reservation_rembourser" boolean NOT NULL, "etat_paiement" varchar(20) NOT NULL, "trajet_payer" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "passager_id" integer NULL);
--
-- Create model TokenValidation
--
CREATE TABLE "main_tokenvalidation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" varchar(128) NOT NULL UNIQUE, "action" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" integer NOT NULL UNIQUE);
--
-- Create model TrajetProposer
--
CREATE TABLE "main_trajetproposer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "etat" varchar(15) NOT NULL, "trajet_rembourser" boolean NOT NULL, "ville_depart" varchar(50) NOT NULL, "ville_arrivee" varchar(50) NOT NULL, "date" date NOT NULL, "heure" time NOT NULL, "places" integer NOT NULL, "prix" numeric(5, 2) NOT NULL, "total_payer" numeric(5, 2) NULL, "temps_trajet" interval NOT NULL, "created_at" timestamp with time zone NULL, "chauffeur_id" integer NOT NULL);
--
-- Add field trajet_reserver to reservationtrajet
--
ALTER TABLE "main_reservationtrajet" ADD COLUMN "trajet_reserver_id" bigint NULL CONSTRAINT "main_reservationtraj_trajet_reserver_id_69e2e838_fk_main_traj" REFERENCES "main_trajetproposer"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "main_reservationtraj_trajet_reserver_id_69e2e838_fk_main_traj" IMMEDIATE;
--
-- Create model ChangerStatutTrajet
--
CREATE TABLE "main_changerstatuttrajet" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "statut" varchar(15) NOT NULL, "modified_at" timestamp with time zone NOT NULL, "trajet_id" bigint NULL);
--
-- Create model Voiture
--
CREATE TABLE "main_voiture" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "marque" varchar(30) NOT NULL, "modele" varchar(50) NOT NULL, "couleur" varchar(50) NOT NULL, "type_moteur" varchar(50) NOT NULL, "places" varchar NOT NULL, "immatriculation" varchar(10) NOT NULL, "annee" integer NOT NULL, "user_id" integer NULL);
--
-- Add field voiture to trajetproposer
--
ALTER TABLE "main_trajetproposer" ADD COLUMN "voiture_id" bigint NULL CONSTRAINT "main_trajetproposer_voiture_id_515ff967_fk_main_voiture_id" REFERENCES "main_voiture"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "main_trajetproposer_voiture_id_515ff967_fk_main_voiture_id" IMMEDIATE;
--
-- Create model NoteUser
--
CREATE TABLE "main_noteuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "note" numeric(2, 1) NULL, "note_attribuee" boolean NOT NULL, "avis" varchar(100) NOT NULL, "avis_donne" boolean NOT NULL, "commentaire" text NULL, "commentaire_attribuee" boolean NOT NULL, "commentaire_moderer" boolean NOT NULL, "etat_paiement" varchar(20) NOT NULL, "decision_prise" boolean NOT NULL, "token" uuid NOT NULL UNIQUE, "chauffeur_id" integer NULL, "passager_id" integer NULL, "trajet_id" bigint NULL);
ALTER TABLE "main_activationtoken" ADD CONSTRAINT "main_activationtoken_user_id_96413ffc_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_activationtoken_token_7b750cf3_like" ON "main_activationtoken" ("token" varchar_pattern_ops);
ALTER TABLE "main_adresseuser" ADD CONSTRAINT "main_adresseuser_user_id_e9f282eb_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_choixrole" ADD CONSTRAINT "main_choixrole_user_id_0d741e37_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_credituser" ADD CONSTRAINT "main_credituser_user_id_986d53f7_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_preference" ADD CONSTRAINT "main_preference_user_preference_id_3a899e9a_fk_auth_user_id" FOREIGN KEY ("user_preference_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_reservationtrajet" ADD CONSTRAINT "main_reservationtrajet_passager_id_5aa7aa70_fk_auth_user_id" FOREIGN KEY ("passager_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_reservationtrajet_passager_id_5aa7aa70" ON "main_reservationtrajet" ("passager_id");
ALTER TABLE "main_tokenvalidation" ADD CONSTRAINT "main_tokenvalidation_user_id_777406f3_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_tokenvalidation_token_ac23985c_like" ON "main_tokenvalidation" ("token" varchar_pattern_ops);
ALTER TABLE "main_trajetproposer" ADD CONSTRAINT "main_trajetproposer_chauffeur_id_02dbde9d_fk_auth_user_id" FOREIGN KEY ("chauffeur_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_trajetproposer_chauffeur_id_02dbde9d" ON "main_trajetproposer" ("chauffeur_id");
CREATE INDEX "main_reservationtrajet_trajet_reserver_id_69e2e838" ON "main_reservationtrajet" ("trajet_reserver_id");
ALTER TABLE "main_changerstatuttrajet" ADD CONSTRAINT "main_changerstatuttr_trajet_id_bcf93a93_fk_main_traj" FOREIGN KEY ("trajet_id") REFERENCES "main_trajetproposer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_changerstatuttrajet_trajet_id_bcf93a93" ON "main_changerstatuttrajet" ("trajet_id");
ALTER TABLE "main_voiture" ADD CONSTRAINT "main_voiture_user_id_70b7f8a7_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_voiture_user_id_70b7f8a7" ON "main_voiture" ("user_id");
CREATE INDEX "main_trajetproposer_voiture_id_515ff967" ON "main_trajetproposer" ("voiture_id");
ALTER TABLE "main_noteuser" ADD CONSTRAINT "main_noteuser_chauffeur_id_passager_id_trajet_id_3296c501_uniq" UNIQUE ("chauffeur_id", "passager_id", "trajet_id");
ALTER TABLE "main_noteuser" ADD CONSTRAINT "main_noteuser_chauffeur_id_cc56b1ec_fk_auth_user_id" FOREIGN KEY ("chauffeur_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_noteuser" ADD CONSTRAINT "main_noteuser_passager_id_137b6830_fk_auth_user_id" FOREIGN KEY ("passager_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_noteuser" ADD CONSTRAINT "main_noteuser_trajet_id_242fb716_fk_main_trajetproposer_id" FOREIGN KEY ("trajet_id") REFERENCES "main_trajetproposer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_noteuser_chauffeur_id_cc56b1ec" ON "main_noteuser" ("chauffeur_id");
CREATE INDEX "main_noteuser_passager_id_137b6830" ON "main_noteuser" ("passager_id");
CREATE INDEX "main_noteuser_trajet_id_242fb716" ON "main_noteuser" ("trajet_id");
COMMIT;